### ISSUE TITLE
remove postgis extension

### ISSUE THREAD

**Issue by adipasquale** [betagouv/collectif-objets#1085]
je crois que ce n’est utilisé que pour `departement.bounding_box_sw`, `departement.bounding_box_ne` on pourrait tout à fait s’en passer

**Comment by bricedurand** [comment]
Justement hier en ré installant ma machine je me suis demandé si on pouvait l'enlever.
Si oui je suis pour s'en débarrasser, ça fait un truc de moins à gérer.

**Comment by adipasquale** [comment]
👍 back to basics
