### ISSUE TITLE
supprimer les notes internes

### ISSUE THREAD

**Issue by adipasquale** [betagouv/collectif-objets#114]
il me semble qu'il faudrait dès maintenant passer à un flux de commentaires plutôt qu'un champ unique

je pense qu'il faut isoler ces notes internes du reste de l'interface, elles ne sont pas très compréhensibles en bas de page. On peut imaginer le faire dans une barre latérale mais ça risque d'être lourd.

on peut aller s'inspirer de Démarches Simplifiées si on retrouve un accès instructeur en staging. De mémoire il y a une navigation par onglet pour chaque dossier et les commentaires privés sont dans un onglet indépendant. Il y a un autre onglet "messagerie" pour échanger avec la commune. Les notes de la commune pourraient apparaître ici

**Comment by adipasquale** [comment]
nous avons décidé au séminaire marseillais de supprimer les notes internes 

est-ce que c'était à la fois les notes à l'échelle de la commune et de l'objet ?

**Comment by Romugoud** [comment]
On a aussi eu un échange sur les échanges de mél avec les communes (ou entre conservateurs à propos de la dite commune) qui pourraient pallier à cette suppression.
