### ISSUE TITLE
Erreur lorsqu'on relance make dev

### ISSUE THREAD

**Issue by bricedurand** [betagouv/collectif-objets#1154]
Depuis le dernier changement sur Procfile.dev (la comande pour lancer mailhog est désormais `mailhog 1> /dev/null`) si je lance un `make dev`, puis fais CTL+C et relance `make dev`, j'ai l'erreur suivante : 
`13:59:42 mailhog.1 | 2024/02/01 13:59:42 [SMTP] Error listening on socket: listen tcp 0.0.0.0:1025: bind: address already in use`

**Comment by adipasquale** [comment]
bien vu ! j’ai corrigé sur https://github.com/betagouv/collectif-objets/commit/ce6a880313123e912413cc5bfede0ff6a33c4733
